### ISSUE TITLE
0.5.0 checklist

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/descriptr#85]
Prepare for release:

* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] Polish NEWS

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [x] `pkgdown::build_site()`
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [x] Bump dev version

Template from <https://github.com/r-lib/usethis/issues/338>
